// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectEmployeeManagement.Data;

#nullable disable

namespace ProjectEmployeeManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230601115344_AddSeedEmployees")]
    partial class AddSeedEmployees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectEmployeeManagement.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("department")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Example20@gmail.com",
                            Name = "Rami",
                            Phone = "774574645",
                            PhotoPath = "",
                            department = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "Example21@gmail.com",
                            Name = "Ali",
                            Phone = "772451639",
                            PhotoPath = "",
                            department = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "Example22@gmail.com",
                            Name = "Doha",
                            Phone = "774574222",
                            PhotoPath = "",
                            department = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
